### ISSUE TITLE
Not compilable at commit 7f13b16

### ISSUE THREAD

**Issue by komaspieler** [qbrobotics/handadmin#3]
Commit 7f13b16 (most recent)  is not compilable due to a missing function declaration for commSetParam and commGetParam:

  ? make

g++ -c -Wall  handmove.c -o ../objs_unix/handmove.o
handmove.c: In function ‘int main(int, char**)’:
handmove.c:461:16: error: ‘commGetParam’ was not declared in this scope
             if(commGetParam(&comm_settings_1, BROADCAST_ID, PARAM_INPUT_MODE, &aux_input, 1) != -1 &&
                ^~~~~~~~~~~~
handmove.c:461:16: note: suggested alternative: ‘commGetParamList’
             if(commGetParam(&comm_settings_1, BROADCAST_ID, PARAM_INPUT_MODE, &aux_input, 1) != -1 &&
                ^~~~~~~~~~~~
                commGetParamList
handmove.c:661:9: error: ‘commSetParam’ was not declared in this scope
         commSetParam(&comm_settings_1, global_args.device_id,
         ^~~~~~~~~~~~
handmove.c:661:9: note: suggested alternative: ‘commSetZeros’
         commSetParam(&comm_settings_1, global_args.device_id,
         ^~~~~~~~~~~~
         commSetZeros
handmove.c: In function ‘void int_handler_2(int)’:
handmove.c:747:5: error: ‘commSetParam’ was not declared in this scope
     commSetParam(&comm_settings_1, global_args.device_id,
     ^~~~~~~~~~~~
handmove.c:747:5: note: suggested alternative: ‘commSetZeros’
     commSetParam(&comm_settings_1, global_args.device_id,
     ^~~~~~~~~~~~
     commSetZeros
  make: *** [makefile:45: ../objs_unix/handmove.o] Error 1

Used handadmin commit: 7f13b16
Used qbAPI commit: c61204b

**Comment by qbrobotics-AR** [comment]
Hi Thomas,

before addressing your issues, I need to know which device (or devices) are you using and since when you have it. In this way I can understand which software is the correct one to use.

Bests,
Alessandro.

**Comment by komaspieler** [comment]
Hi Alessandro,

thank you for the swift reply! I'm part of the RBO Robotics Lab at TU Berlin, we are using the Pisa/IIT Softhand with Firmware "SH-PRO v5.2.6".

We have used the handadmin tool and qbAPI successfully before. The last working & compilable version we are able to access is eff1ec8

Cheers,
Thomas

**Comment by qbrobotics-AR** [comment]
Ok, thanks for all the detailed informations.
According to the hand firmware version, you need to use the qbAPI version 87b034c 
The compilation errors you are encountering are due to a mismatched version of qbAPI (v6.x.x) and handadmin (v5.x.x) which are non retro compatible.

Let me know if with the correct API version you are able to use the software.
Bests,
Alessandro

**Comment by komaspieler** [comment]
That works beautifully, thank you!
